name: Build check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        cd express-ts-sequelize
        npm install

    - name: Build Code
      run: |
        cd express-ts-sequelize
        npm run build
