name: Build check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging Step
      run: |
        echo "Current working directory: $(pwd)"
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        echo "List of files: $(ls -la)"
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Code
        run: |
          npm run build
